title = "AstroFlash"
baseURL = "https://astroflash-frb.github.io"
languageCode = "en-us"
theme = ["ananke"]
resourceDir = "resources"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
menu = ["about", "posts", "contact"]

[markup.goldmark.renderer]
    safeMode = 'unsafe'


[languages]
    [languages.en]
        title = "AstroFlash"
        weight = 1
        contentDir = "content/"

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    text_color = ""
    author = ""
    favicon = "logo.svg"
    site_logo = "Astroflash-logo.png"
    description = "The last theme you'll ever need. Maybe."
    # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-black"
    recent_posts_number = 3
    background_image = 'static/cover.jpg'
    data_format = "2 January 2006"

[[params.ananke_socials]]
    # name = "twitter"
    # url = "https://twitter.com/GoHugoIO"
    name = "github"
    url = "https://github.com/orgs/astroflash-frb/teams/astroflash"
